version: '3.7'

services:
  zabbix-server:
    image: zabbix/zabbix-server-php
    volumes:
      - ./zabbix:/configuration
    ports:
      - '10051:10051'
      - '80:80'
  zabbix-web:
    image: zabbix/zabbix-web-php
    depends_on:
      - zabbix-server
    volumes:
      - ./zabbix:/configuration
    ports:
      - '8080:80'
