name: Push Existing Docker Image

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Load Docker image from file
      run: docker load -i ./path/to/your-docker-image.tar

    - name: Tag Docker image
      run: docker tag your-docker-image:tag ${{ secrets.DOCKER_USERNAME }}/nginx:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest
